---
title: "Corona Virus Report"
author:
- familyname: Jiang
  othernames: Vivee
  address: Monash Universtidy
  email: yjia0142@student.monash.edu
- familyname: Jaiswal
  othernames: Prachi
  address: Monash University
  email: pjai0005@student.monash.edu
- familyname: Jawahar
  othernames: Sithalakshmi
  address: Monash University
  email: sja0002@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
always_allow_html: true
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)
library(plotly)
library(ggthemes)
library(gridExtra)
library(kableExtra)
library(rmdformats)
```

```{r}
cases <- read_csv("Data/worldwidecases.csv")
```

This is the introduction all of us have to use. Let's figure out how to do it! 

\section*{Country China and Thailand"}
```{r}
cases<- read_csv("~/git/Tutorial8/Data/worldwidecases.csv")
```

```{r}
China_cases <- cases %>% filter(countriesAndTerritories== "China")
china_cases <- China_cases %>% select(month, cases)
    
ggplot(China_cases, aes(x = dateRep,
y = cases)) +
  geom_line() +
  xlab("Date") + 
  ylab("Cases") +
theme_bw()
china_cases
```



\section*{Country India and Singapore}

```{r}
sjcountries <- cases %>% 
  dplyr::filter(countriesAndTerritories %in% c ("India", "Singapore"))

```


\section*{Country XX3 and YY3}
```{r filtering, echo=FALSE, warning=FALSE, message=FALSE}
case <- read_csv("Data/worldwidecases.csv")

case_i <- case %>% filter(countriesAndTerritories== "Italy")
case_f <- case %>% filter(countriesAndTerritories== "France")

corona <- full_join (case_i, case_f,
                         by = NULL, copy = FALSE,
                         suffix = c(".italy", ".france"))
write.csv (corona, here::here("Data/data.csv"))

corona_data <- read_csv("Data/data.csv")

```

```{r italy, echo=FALSE, warning=FALSE, message=FALSE}

  ggplot(corona_data, 
         aes(x= month,
             y= cases))+
  geom_bar(stat = 'identity') +
  theme_economist_white() +
  ggtitle("Comparing countries wrt Cases")+
scale_x_continuous(breaks=c(0:12))+
 facet_wrap(~countriesAndTerritories) 
ggplotly()
```


```{r france, echo=FALSE, warning=FALSE, message=FALSE}
   ggplot(corona_data, 
         aes(x= month,
             y= deaths))+
  geom_bar(stat = 'identity') +
  theme_economist_white() +
  ggtitle("Comparing countries wrt Deaths")+
scale_x_continuous(breaks=c(0:12))+
 facet_wrap(~countriesAndTerritories) 
ggplotly()
```
```{r reg, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(data = corona_data, aes(x = deaths, y = cases,
 color = factor(countriesAndTerritories))) +
 geom_point(alpha = 0.4) +
scale_x_continuous(breaks = seq(0, 2005, by = 400))+
 # theme(legend.position = "bottom",
        # axis.text.x= element_text(angle = 50, hjust= 1, vjust = 1))+ #shows text of x axis in an angle.)
 geom_smooth(method = "lm", se = FALSE, colour= "green") +
 labs(color = "countriesAndTerritories") +
 scale_colour_viridis_d()
#scale_colour_brewer(palette = "set1")
ggplotly()

```


```{r table, echo=FALSE, warning=FALSE, message=FALSE}
t1 <- corona_data %>% 
  group_by(month) %>%
  count(deaths, cases) 
  
  # pivot_wider(id_cols = Type,
  #               names_from = Colour,
  #               values_from= n) %>%
  # knitr::kable(caption = "Cases") %>%
  #  kable_styling(bootstrap_options = c( "hover" , "bordered", "striped"))
t1
```

